### ISSUE TITLE
Allow Extended Dot Syntax [enhancement]

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/PipeScript#273]
[Dot syntax](https://github.com/StartAutomating/PipeScript/blob/main/Transpilers/Syntax/Dot.psx.ps1#L18https://github.com/StartAutomating/PipeScript/blob/main/Transpilers/Syntax/Dot.psx.ps1#L18)

- [ ] extended, multi-line syntax
- [ ] Can simple properties complete?

## [ ] Mutli-line properties

Easier line continuations could be nice. The complexity of parsing makes me wonder how feasible that is. 
Additional complexity is from having what appears to be a continuation, can be a new object
```ps1
# base
.> { 
    1 | # one object
    .Number { $_ } .Even { -not ($_ % 2) } .Odd { ($_ % 2) -as [bool] } }

.> { 
    1 | # 2 objects objects
    .Number { $_ }
    .Even { -not ($_ % 2) } .Odd { ($_ % 2) -as [bool] } }
```
This is the rare case where backticks are nice. 
```ps1
.> { 
    1 | # 1 objects object
    .Number { $_ } `
    .Even { -not ($_ % 2) } .Odd { ($_ % 2) -as [bool] } }
```

## [ ] Can simple properties complete?

> If it is followed by a ScriptBlock, a dynamic property will be created that will return the result of that script block.

Is this why autocomplete doesn't work for properties?  For example:

```ps1
# pipescript v0.1.8
$x = Invoke-PipeScript { 
    Get-ChildItem . | Select-Object -First 1 
    | .Name .LastWriteTime
 } -ov 'ov'
```
There's no completions when using `$x.` then <kbd>Tab</kbd> or <kbd>Ctrl</kbd> + <kbd>Space</kbd>
Interestingly not even for builtins like `ToString()` or memberType `NoteProperty` . I double checked, they do exist, they just don't complete. 

However, 
```ps1
$x2 = $x | Select
```
`$x2` does complete. I thought maybe it's implicitly using `select *` creating a new PSCO. So I tried the syntax that I thought didn't mutate the original -- when using counts
```ps1
$z3 = $z | select -First 1
```
`$x3` also completes.

**Comment by StartAutomating** [comment]
@ninmonkey both of these are fairly complex, and should be separate issues.

The former is the "more" simple one.  Basically, this is "transpilers can only modify themselves" or "transpilers should be able to extend their replacement range".  Essentially, when a newline is encountered, PowerShell considers this a break in commands.  Thus even if one could make the transpiler notice "hey, the next command is also .something", the overall engine does not _yet_ support saying "so include that content in what is transpiled".

It should.

The latter one is a whole big-old-can of worms, which is "how do you complete something that doesn't yet exist"?

The first half of this I'm eager to get to, because it opens up a number of other doors.

The latter one I'm less inclined to charge at, because there are many facets of making it work.
